name: ci
on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup example
        run: |
          mkdir -p demo/.fluentci
          cp -r src demo/.fluentci
          cp Cargo.toml demo/.fluentci
          cp Cargo.lock demo/.fluentci
      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            setup
            test
            compile
            package
          working-directory: demo
      - name: Show sbt version, run tests and build
        run: |
          type sbt
          sbt --version
        working-directory: demo
